# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e7f398088b72e2c5c433db9241fd75e89bb6b160336519b3d4355bed38a8e92a2506e2c7a02febe148fa2dedd2585b7981c4fa907a23b9dd3f9ffdba2e6c1a

test:
  secret_key_base: 874cdfe7f984a7cbc0fe95940b780fca3d5e2f385fe001d4f3bce3394acf64e6810692f58447ec82f4cccacf9b1739bfb193d4f15349a6eb3e54d48132822607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
